#!/bin/sh

if [ "$1" = "remove" ]; then
    nautilus_extension_directory="/usr/lib/x86_64-linux-gnu/nautilus/extensions-3.0/"
    if [ -d "${nautilus_extension_directory}" ]; then
        rm -f "${nautilus_extension_directory}/libslika-nautilus.so"
    fi
fi
